### ISSUE TITLE
Can't access metrics on Triton

### ISSUE THREAD

**Issue by ksketo** [autopilotpattern/nginx#17]
When I run this project locally I can view the telemetry page on :9090/metrics. However when I deploy on Triton and try to access with `open http://$(triton ip nginx_nginx_1):9090/metrics` the page fails to open. All services are registered on consul and I can also see the containerpilot service with port 9090 exposed on the same node with nginx.

**Comment by tgross** [comment]
What IP address is the ContainerPilot marked as listening on? I suspect it's only listening on the private Triton IP, which you won't be able to reach from the public Internet. You'd need to set the `interfaces` field for the telemetry stanza like so:

`interfaces": ["eth1", "eth0"],`

(It occurs to me this is also missing in our `services` stanza, so I imagine you're not getting the Nginx home page either? That's definitely mistake and not how we're doing it in e.g. https://github.com/autopilotpattern/workshop/blob/master/nginx/containerpilot.json)

**Comment by ksketo** [comment]
Yes, ContainerPilot was listening on the private Triton IP. Setting the interfaces field for the telemetry stanza, solved my problem :)
