### ISSUE TITLE
running consul agent coprocess on swarm

### ISSUE THREAD

**Issue by ilpoldo** [autopilotpattern/nginx#24]
Hi, if I run on my docker machine host:

     docker-compose -f local-compose.yml up

For the example service I see the agent connecting and reporting:

    example_1  | Service not registered, registering...
    example_1  | 2016/08/22 10:32:42     2016/08/22 10:32:42 [INFO] agent: Synced service 'example-0ca8047f8fd1'
    example_1  | 2016/08/22 10:32:42     2016/08/22 10:32:42 [INFO] agent: Synced check 'example-0ca8047f8fd1'

And get:

    curl -L http://$(docker-machine ip default):8500/v1/catalog/nodes
    [{"Node":"0ca8047f8fd1","Address":"172.17.0.3"},
     {"Node":"dde547c466bc","Address":"172.17.0.4"},
     {"Node":"f2ae28edc5e1","Address":"172.17.0.2"}]

If I try do do the same (using a 3 node consul cluster) with service using docker 1.12 swarm mode:

    docker network create -d overlay autopilot

    docker service create --name consul  -e CONSUL=consul \
    --network autopilot --replicas 3 -p 8500:8500/tcp \
    autopilotpattern/consul /usr/local/bin/containerpilot /bin/consul agent \
    -server -bootstrap-expect 3 \
    -config-dir=/etc/consul -ui-dir /ui

    docker service create --name example -e CONSUL_AGENT=1 -e CONSUL=consul \
    -p 4000:4000/tcp autopilotpattern/nginx-example-app

The log for `example` is stuck at:

    Service not registered, registering...

and the consul servers keep printing to their log:

    2016/08/22 10:55:42 [INFO] agent.rpc: Accepted client: 127.0.0.1:60004
    2016/08/22 10:55:52 [INFO] agent.rpc: Accepted client: 127.0.0.1:60016

If I check the node catalog in consul I only see the three consul servers:

    curl -L http://$(docker-machine ip default):8500/v1/catalog/nodes
    [{"Node":"7ce9d92923ca","Address":"10.0.0.5","TaggedAddresses":{"wan":"10.0.0.5"},"CreateIndex":3,"ModifyIndex":15},
     {"Node":"a2277eb1eacd","Address":"10.0.0.4","TaggedAddresses":{"wan":"10.0.0.4"},"CreateIndex":4,"ModifyIndex":14},
     {"Node":"fefe0149e59e","Address":"10.0.0.3","TaggedAddresses":{"wan":"10.0.0.3"},"CreateIndex":5,"ModifyIndex":17}]

My guess is that the consul agent coprocess is not binding the right ip address, perhaps because of to the configuration of the network interfaces in the containers launched by swarm, and I can't think of an easy way to configure it using autoptilot.json. Is there a way to specify the network interface to determine the ip address to bind to via env variable like `CONSUL_BIND_INTERFACE` used by the [official consul image](https://hub.docker.com/_/consul/)  or something similar?

EDIT: formatting

**Comment by tgross** [comment]
> If I try do do the same (using a 3 node consul cluster) with service using docker 1.12 swarm mode:

Just for starters, I'm not sure I'd bother using a Consul agent coprocess in a swarm deployment, given that swarm has an assumption of multiple Docker hosts where you could deploy a Consul agent on each. But this *should* work so let's dig into why...

> My guess is that the consul agent coprocess is not binding the right ip address, perhaps because of to the configuration of the network interfaces in the containers launched by swarm

I can only guess myself without having more detailed logs (if you run with DEBUG logging on we'll get a lot more information) or having you check inside the running container via `docker exec` to see what has bound to what interfaces.

ContainerPilot exposes an environment variable `CONTAINERPILOT_{SERVICE_NAME}_IP` in the containerpilot templating (as found under "services" in the [configuration docs](https://www.joyent.com/containerpilot/docs/configuration). You could have your coprocess config use `-bind {{ .CONTAINERPILOT_EXAMPLE_IP }}` to have it bind to the same address.

Alternately, verify that you're not running into late binding of the interface as someone found with Weave here: https://github.com/joyent/containerpilot/issues/181. I don't *think* Swarm overlay has this same bug but it couldn't hurt to check.

**Comment by ilpoldo** [comment]
Thanks for the links and the suggestions. I have had a look at those issues and tried to do some debugging: I made a small repo to reproduce the issue launching the various services in the example on swarm and compose: [ilpoldo/autopilotpattern-nginx-24](https://github.com/ilpoldo/autopilotpattern-nginx-24).

I can print the `CONTAINERPILOT_{SERVICE_NAME}_IP` in the `preStart` and in the script launched as coprocesses, but it does not seem to substitute with the IP address in the `containerpilot.json` itself.

I made a separate branch performing the substitution in a shell script and the coprocess runs fine.
Even when running in compose the ip substitution does not come through (should be after `-bind` in the line below) but it does not affect the behaviour of the tool.

    2016/08/22 16:45:46 coprocess[/usr/local/bin/consul agent -data-dir=/data -config-dir=/config -bind  -log-level debug -rejoin -retry-join consul -retry-max 10 -retry-interval 10s].Start

Reading the docs I ended up thinking that having a consul agent running per container was the intended way of using containerpilot even if service discovery and load balancing was taken care of by swarm.  Having individual containers show up as nodes providing multiple (not many) services seemed like the "right way" of using consul and that it somehow meant better performance for watching configuration changes across the application and collect health check results.

**Comment by tgross** [comment]
Can you provide your DEBUG logs and your ContainerPilot configuration file?

**Comment by ilpoldo** [comment]
The [config file](https://github.com/ilpoldo/autopilotpattern-nginx-24/blob/e3b6ef6c69dc5ab99c030d143982a46f8d3fe437/example-backend/containerpilot.json).

And the logs of the example application service/container running in swarm and compose:

[compose.txt](https://github.com/autopilotpattern/nginx/files/430829/compose.txt)
[swarm.txt](https://github.com/autopilotpattern/nginx/files/430830/swarm.txt)

**Comment by tgross** [comment]
Ok here's the relevant bit:

```
2016/08/22 17:56:10 coprocess[/usr/local/bin/consul agent -data-dir=/data -config-dir=/config -bind  -log-level debug -rejoin -retry-join consul -retry-max 10 -retry-interval 10s].Start
```

There are two things I see here:

`-retry-join consul` isn't going to work unless you've linked the container to Consul so that you have the DNS name made available. Which it looks like you're doing in the `compose.txt` log but not in the `swarm.txt` log.

You can see there's two spaces between `-bind` and `-log-level` in that command line, which means `{{ .CONTAINERPILOT_EXAMPLE_IP }}` is blank. I dug into why and realized that I accidentally mislead you here -- that environment variable is available to child processes but not to the ContainerPilot configuration. The reason is that the config file has to be fully parsed before we can set the environment variable, because the environment variable is derived from the config.

You may want to consider having your `preStart` write this value into the coprocess config section and SIGHUP ContainerPilot, or having a `preStart` write the appropriate values into a Consul config file rather than passing them in on the command line.

**Comment by ilpoldo** [comment]
Thanks, that makes sense. Once the bind address is in place everything else works fine: creating a service on swarm means providing a dns name to the other containers on the same network, so in my swarm example there is no need to link the containers.

On [the branch with a possible solution](https://github.com/ilpoldo/autopilotpattern-nginx-24/tree/consul_coprocess_fix) I ended up wrapping the coprocess in a launcher script instead of updating the `autopilot.json` as part of the `preStart`.
Feel free to close the ticket.

**Comment by tgross** [comment]
Ok, I'm going to close this and consider coming up with a way to have that env variable available via a second pass at template rendering or something.
