### ISSUE TITLE
http_stub_status_module

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/nginx#3]
First, I need to test this, but I'm looking at the docs in [http_stub_status_module](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html) and getting excited about how we can use it to understand instance performance.

Suggested config from one source on the internet (so it must be gospel):

```
location /nginx_status {
  stub_status on;
  access_log   off;
  allow 127.0.0.1;
  deny all;
}
```

What I'm looking for:

- `Active connections` vs. the [`worker_connections `](http://nginx.org/en/docs/ngx_core_module.html#worker_connections) limit is a critical number.
- Any delta between `accepts` and `handled` is a huge red flag. 
- The `Waiting` number is an inverse indicator of activity. High numbers indicate low activity, low numbers indicate high activity, zero _could_ mean requests are going unanswered.

I'm thinking about all this in the context of [KPIs that might be Configured in and reported by Containerbuddy](https://github.com/joyent/containerbuddy/issues/27).

**Comment by tgross** [comment]
ref https://github.com/tgross/triton-elk/blob/master/nginx/nginx.conf#L38-L42 for an example of that exact configuration in play. I used this at DF to gather stats from Nginx via collectd and then sent them off to graphite.

**Comment by misterbisson** [comment]
Was proposed in conjunction with https://github.com/joyent/containerpilot/issues/27, which was added in https://github.com/joyent/containerpilot/issues/123, and delivered as https://github.com/joyent/containerpilot/releases/tag/2.0.0

Now closing this issue in favor of https://github.com/autopilotpattern/nginx/issues/10
